apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator
  labels:
    app: calculator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      volumes:
        - name: encrypted-conf
          persistentVolumeClaim:
            claimName: hostpath-calculator-conf-pvc
        - name: decrypted-conf
          emptyDir: {}
      initContainers:
        - name: decrypt-env
          image: alpine:3.16
          command:
            - sh
            - -c
            - |
              # install GPG, decrypted into the emptyDir \
              apk add --no-cache gnupg && \
              gpg --batch --yes \
              --passphrase "$GPG_PASSPHRASE" \
              -o /mnt/decrypted/.env \
              -d /mnt/secrets/.env.dev.gpg
          env:
            - name: GPG_PASSPHRASE
              valueFrom:
                secretKeyRef:
                  name: gpg-passphrase
                  key: GPG_PASSPHRASE
          volumeMounts:
            - name: encrypted-conf
              mountPath: /mnt/secrets
              readOnly: true
            - name: decrypted-conf
              mountPath: /mnt/decrypted
      containers:
      - name: calculator
        image: calculator:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: CALCULATOR_CONF_FILE
            value: /mnt/decrypted/.env
        volumeMounts:
          - name: decrypted-conf
            mountPath: /mnt/decrypted
            readOnly: true
        args:
          - "--server.baseUrlPath"
          - "/calculator"
        ports:
        - containerPort: 8501
          name: web
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /calculator/_stcore/health
            port: 8501
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /calculator/_stcore/health
            port: 8501
          initialDelaySeconds: 5
          periodSeconds: 5
