apiVersion: v1
kind: Pod
metadata:
  name: tester-hostpath
spec:
  containers:
    - name: busy
      image: busybox
      command: [ "sh", "-c", "echo hello > /conf/hello.txt; sleep 3600" ]
      volumeMounts:
        - name: conf
          mountPath: /conf
  volumes:
    - name: conf
      persistentVolumeClaim:
        claimName: pvc-calculator-conf
