apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hostpath-calculator-conf-pvc
spec:
  storageClassName: manual-hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: calculator
      datatype: conf